#!/usr/bin/env python3
"""Dimension-only resource planning for annotation-context covariance.

The calculator allocates no dimension-sized numeric arrays.  It independently
audits the public resource estimator against exact integer formulas for the
declared grouped and SNP-level storage layouts.  A hard cap can be applied to
either the current dense Python development backend or the planned streamed
operator backend.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
import json
import math
import os
import resource
import sys
from pathlib import Path
from typing import Any, Sequence

from summit.context import AnnotationResourceRequest, estimate_annotation_resources


OUTPUT_NAME = "08_context_annotation_resource_dry_run.json"
FLOAT64_BYTES = 8
INT64_BYTES = 8


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--n-reference", type=int, default=100_000)
    parser.add_argument("--n-study", type=int, default=500_000)
    parser.add_argument("--m", type=int, default=1_000_000)
    parser.add_argument("--q-values", default="2,3,4")
    parser.add_argument("--k-values", default="1,4,8")
    parser.add_argument("--loo-groups", type=int, default=200)
    parser.add_argument("--residual-components", type=int, default=2)
    parser.add_argument("--gram-probes", type=int, default=128)
    parser.add_argument("--same-person-probes", type=int, default=128)
    parser.add_argument("--probe-tile-size", type=int, default=8)
    parser.add_argument("--variant-probe-tile-size", type=int, default=8)
    parser.add_argument("--trait-block-size", type=int, default=256)
    parser.add_argument(
        "--memory-cap-gib",
        type=float,
        default=64.0,
        help="Hard cap for the modeled grouped-operator peak resident bytes.",
    )
    parser.add_argument(
        "--probe-panel-policy",
        choices=("full", "counter_generated_tiles"),
        default="full",
        help="Whether complete probe panels are resident or generated by tile.",
    )
    parser.add_argument(
        "--cap-backend",
        choices=("current_python_grouped_hutch_ustat", "grouped_operator_target"),
        default="current_python_grouped_hutch_ustat",
        help="Backend peak against which the hard memory cap is enforced.",
    )
    parser.add_argument("--overwrite", action="store_true")
    return parser


def _integer_list(
    parser: argparse.ArgumentParser, text: str, label: str
) -> tuple[int, ...]:
    try:
        values = tuple(int(item.strip()) for item in text.split(",") if item.strip())
    except ValueError:
        parser.error(f"{label} must be a comma-separated integer list")
    if not values or any(value < 1 for value in values):
        parser.error(f"{label} must contain positive integers")
    if len(values) != len(set(values)):
        parser.error(f"{label} must not contain duplicates")
    return values


def _validate(parser: argparse.ArgumentParser, args: argparse.Namespace) -> None:
    positive = {
        "--n-reference": args.n_reference,
        "--n-study": args.n_study,
        "--m": args.m,
        "--loo-groups": args.loo_groups,
        "--residual-components": args.residual_components,
        "--gram-probes": args.gram_probes,
        "--same-person-probes": args.same_person_probes,
        "--probe-tile-size": args.probe_tile_size,
        "--variant-probe-tile-size": args.variant_probe_tile_size,
        "--trait-block-size": args.trait_block_size,
    }
    for label, value in positive.items():
        if isinstance(value, bool) or value < 1:
            parser.error(f"{label} must be a positive integer")
    if args.n_reference < 2:
        parser.error("--n-reference must be at least 2")
    if args.loo_groups > args.m:
        parser.error("--loo-groups cannot exceed --m")
    if args.same_person_probes < 2:
        parser.error("--same-person-probes must be at least 2")
    if not math.isfinite(args.memory_cap_gib) or args.memory_cap_gib <= 0.0:
        parser.error("--memory-cap-gib must be finite and positive")


def _ceil_div(numerator: int, denominator: int) -> int:
    return (numerator + denominator - 1) // denominator


def _rss_bytes() -> int:
    value = int(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
    return value if sys.platform == "darwin" else value * 1024


def _bytes(elements: int) -> int:
    return FLOAT64_BYTES * elements


def _case(
    *,
    n_reference: int,
    n_study: int,
    m_variants: int,
    q_count: int,
    k_count: int,
    groups: int,
    residual_count: int,
    gram_probes: int,
    same_person_probes: int,
    probe_tile: int,
    variant_probe_tile: int,
    trait_block: int,
    probe_panel_policy: str,
    memory_cap_bytes: int,
) -> dict[str, Any]:
    pair_count = q_count * (q_count + 1) // 2
    p_genetic = k_count * pair_count
    p_total = p_genetic + residual_count
    gram_tiles = _ceil_div(gram_probes, probe_tile)
    same_person_tiles = _ceil_div(same_person_probes, variant_probe_tile)
    trait_blocks = _ceil_div(m_variants, trait_block)

    reference_core = _bytes(k_count + 2 * p_genetic**2)
    grouped_reference_contributions = _bytes(groups * p_genetic**2)
    snp_reference_contributions = _bytes(m_variants * p_genetic**2)
    grouped_reference_group_masses = _bytes(groups * k_count)
    snp_reference_annotation_weights = _bytes(m_variants * k_count)
    group_variant_counts = INT64_BYTES * groups
    grouped_reference_loo_total = (
        grouped_reference_contributions
        + grouped_reference_group_masses
        + group_variant_counts
    )
    snp_reference_loo_total = (
        snp_reference_contributions + snp_reference_annotation_weights
    )
    grouped_reference_total = reference_core + grouped_reference_loo_total
    snp_reference_total = reference_core + snp_reference_loo_total

    trait_core_elements = (
        k_count
        + p_genetic * (2 + residual_count)
        + 2 * residual_count
        + residual_count**2
    )
    trait_core = _bytes(trait_core_elements)
    grouped_trait_contributions = _bytes(groups * p_genetic * (2 + residual_count))
    snp_trait_contributions = _bytes(m_variants * p_genetic * (2 + residual_count))
    grouped_trait_group_masses = _bytes(groups * k_count)
    snp_trait_annotation_weights = _bytes(m_variants * k_count)
    grouped_trait_loo_total = (
        grouped_trait_contributions + grouped_trait_group_masses + group_variant_counts
    )
    snp_trait_loo_total = snp_trait_contributions + snp_trait_annotation_weights
    grouped_trait_total = trait_core + grouped_trait_loo_total
    snp_trait_total = trait_core + snp_trait_loo_total

    full_gram_panel = _bytes(n_reference * gram_probes)
    tiled_gram_panel = _bytes(n_reference * min(gram_probes, probe_tile))
    full_variant_panel = _bytes(m_variants * same_person_probes)
    tiled_variant_panel = _bytes(
        m_variants * min(same_person_probes, variant_probe_tile)
    )
    resident_gram_panel = (
        full_gram_panel if probe_panel_policy == "full" else tiled_gram_panel
    )
    resident_variant_panel = (
        full_variant_panel if probe_panel_policy == "full" else tiled_variant_panel
    )

    gram_projected_probe = _bytes(n_reference * probe_tile)
    gram_source_sketch = _bytes(q_count * m_variants * probe_tile)
    gram_annotation_weighted_source_sketch = _bytes(k_count * m_variants * probe_tile)
    gram_target_sketch = _bytes(k_count * n_reference * probe_tile)
    gram_action_tile = _bytes(n_reference * probe_tile * p_genetic)
    gram_accumulator = _bytes(p_genetic**2)
    reference_gram_operator_peak = sum(
        (
            grouped_reference_total,
            resident_gram_panel,
            gram_projected_probe,
            gram_source_sketch,
            gram_target_sketch,
            gram_action_tile,
            gram_accumulator,
        )
    )

    same_basis_sketch = _bytes(k_count * q_count * n_reference * variant_probe_tile)
    same_g_tile = _bytes(p_genetic * n_reference * variant_probe_tile)
    same_running_sum = _bytes(n_reference * p_genetic)
    same_cross_accumulator = _bytes(p_genetic**2)
    reference_same_person_operator_peak = sum(
        (
            grouped_reference_total,
            resident_variant_panel,
            same_basis_sketch,
            same_g_tile,
            same_running_sum,
            same_cross_accumulator,
        )
    )

    trait_feature_block = _bytes(q_count * n_study * trait_block)
    trait_score_rhs = _bytes(n_study * q_count)
    trait_score_block = _bytes(trait_block * q_count)
    trait_group_index = INT64_BYTES * m_variants
    trait_operator_peak = sum(
        (
            grouped_trait_total,
            trait_feature_block,
            trait_score_rhs,
            trait_score_block,
            trait_group_index,
        )
    )

    equation_elements = p_total**2 + 2 * p_total + k_count + 2 * p_genetic**2
    equation_bytes = _bytes(equation_elements)
    # The current fitter retains every LOO equation through derived-output
    # construction.  This is an explicit conservative peak term, not required
    # by the mathematical target.
    retained_loo_equations = groups * equation_bytes
    fit_result_core = _bytes(
        2 * p_total**2
        + groups * p_total
        + 5 * p_total
        + p_genetic
        + residual_count
        + k_count * q_count**2
    )
    fit_peak = sum(
        (
            grouped_reference_total,
            grouped_trait_total,
            equation_bytes,
            retained_loo_equations,
            fit_result_core,
        )
    )
    grouped_operator_peak = max(
        reference_gram_operator_peak,
        reference_same_person_operator_peak,
        trait_operator_peak,
        fit_peak,
    )

    dense_features = _bytes(q_count * n_reference * m_variants)
    partition_annotations = _bytes(m_variants * k_count)
    dense_kernels = _bytes(p_genetic * n_reference**2)
    exact_raw_targets = _bytes(p_genetic * q_count * m_variants)
    exact_contribution_transient = _bytes(groups * p_genetic**2)
    dense_reference_development_peak_lower_bound = sum(
        (
            grouped_reference_total,
            partition_annotations,
            dense_features,
            2 * dense_kernels,
            exact_raw_targets,
            exact_contribution_transient,
        )
    )
    hutch_raw_actions = _bytes(p_genetic * n_reference * probe_tile)
    hutch_feature_probe = _bytes(q_count * m_variants * probe_tile)
    hutch_feature_action = _bytes(p_genetic * q_count * m_variants * probe_tile)
    hutch_group_symmetrization_copy = _bytes(groups * p_genetic**2)
    hutch_action_phase = sum(
        (
            grouped_reference_total,
            partition_annotations,
            dense_features,
            resident_gram_panel,
            gram_projected_probe,
            gram_source_sketch,
            _bytes(k_count * q_count * n_reference * probe_tile),
            gram_action_tile,
        )
    )
    hutch_contribution_phase = sum(
        (
            grouped_reference_total,
            partition_annotations,
            dense_features,
            resident_gram_panel,
            gram_action_tile,
            hutch_raw_actions,
            hutch_feature_probe,
            hutch_feature_action,
            hutch_group_symmetrization_copy,
        )
    )
    same_person_sqrt_weights = _bytes(m_variants * k_count)
    current_same_person_source = _bytes(
        k_count * q_count * n_reference * variant_probe_tile
    )
    current_same_person_g = _bytes(p_genetic * n_reference * variant_probe_tile)
    hutch_same_person_phase = sum(
        (
            grouped_reference_total,
            partition_annotations,
            dense_features,
            resident_variant_panel,
            same_person_sqrt_weights,
            current_same_person_source,
            current_same_person_g,
            same_running_sum,
            same_cross_accumulator,
        )
    )
    current_hutchinson_python_peak = max(
        hutch_action_phase, hutch_contribution_phase, hutch_same_person_phase
    )
    current_trait_python_peak = trait_operator_peak + partition_annotations
    current_python_workflow_peak = max(
        current_hutchinson_python_peak, current_trait_python_peak, fit_peak
    )

    source_gemms_per_gram_tile = q_count
    target_gemms_per_gram_tile = k_count * q_count
    exact_kernel_gemms = k_count * q_count**2
    off_diagonal_components = k_count * q_count * (q_count - 1) // 2
    exact_contribution_kernel_feature_gemms = p_genetic * (
        q_count + off_diagonal_components
    )

    independent = {
        "dimensions": {
            "n_reference": n_reference,
            "n_study": n_study,
            "m_variants": m_variants,
            "q": q_count,
            "k": k_count,
            "context_pairs": pair_count,
            "p_genetic": p_genetic,
            "residual_components": residual_count,
            "p_total": p_total,
            "loo_groups": groups,
        },
        "storage_bytes": {
            "reference_core": reference_core,
            "reference_grouped_contribution_tensor": grouped_reference_contributions,
            "reference_snp_contribution_tensor": snp_reference_contributions,
            "reference_grouped_annotation_mass_table": grouped_reference_group_masses,
            "reference_snp_annotation_weight_table": snp_reference_annotation_weights,
            "group_variant_count_array": group_variant_counts,
            "reference_grouped_loo_total_numeric_sufficient_statistics": (
                grouped_reference_loo_total
            ),
            "reference_grouped_total": grouped_reference_total,
            "reference_snp_loo_total_numeric_sufficient_statistics": (
                snp_reference_loo_total
            ),
            "reference_snp_total": snp_reference_total,
            "trait_core": trait_core,
            "trait_grouped_contribution_tensors": grouped_trait_contributions,
            "trait_snp_contribution_tensors": snp_trait_contributions,
            "trait_grouped_annotation_mass_table": grouped_trait_group_masses,
            "trait_snp_annotation_weight_table": snp_trait_annotation_weights,
            "trait_grouped_loo_total_numeric_sufficient_statistics": (
                grouped_trait_loo_total
            ),
            "trait_grouped_total": grouped_trait_total,
            "trait_snp_loo_total_numeric_sufficient_statistics": (snp_trait_loo_total),
            "trait_snp_total": snp_trait_total,
            "grouped_reference_reduction_factor": (
                snp_reference_loo_total / grouped_reference_loo_total
            ),
            "grouped_trait_reduction_factor": (
                snp_trait_loo_total / grouped_trait_loo_total
            ),
        },
        "probe_and_action_bytes": {
            "gram_probe_panel_full": full_gram_panel,
            "gram_probe_panel_tiled": tiled_gram_panel,
            "gram_probe_panel_resident_by_policy": resident_gram_panel,
            "variant_probe_panel_full": full_variant_panel,
            "variant_probe_panel_tiled": tiled_variant_panel,
            "variant_probe_panel_resident_by_policy": resident_variant_panel,
            "gram_projected_probe_tile": gram_projected_probe,
            "gram_source_sketch_q_by_m_by_tile": gram_source_sketch,
            "gram_annotation_weighted_source_sketch_k_by_m_by_tile": (
                gram_annotation_weighted_source_sketch
            ),
            "gram_target_sketch_k_by_n_by_tile_streamed_over_q": (gram_target_sketch),
            "gram_action_tile_n_by_pg_by_tile": gram_action_tile,
            "gram_accumulator_pg_squared": gram_accumulator,
            "same_person_basis_sketch_kq_by_n_by_tile": same_basis_sketch,
            "same_person_g_tile_n_by_pg_by_tile": same_g_tile,
            "same_person_running_sum_n_by_pg": same_running_sum,
            "same_person_cross_accumulator_pg_squared": same_cross_accumulator,
            "current_python_hutch_raw_actions": hutch_raw_actions,
            "current_python_hutch_feature_probe_q_by_m_by_tile": hutch_feature_probe,
            "current_python_hutch_feature_action_pg_by_q_by_m_by_tile": (
                hutch_feature_action
            ),
        },
        "phase_peak_bytes": {
            "reference_gram_grouped_operator": reference_gram_operator_peak,
            "reference_same_person_grouped_operator": (
                reference_same_person_operator_peak
            ),
            "trait_grouped_operator": trait_operator_peak,
            "fit_grouped_current_retention_policy": fit_peak,
            "grouped_operator_workflow_maximum": grouped_operator_peak,
            "current_dense_python_reference_lower_bound": (
                dense_reference_development_peak_lower_bound
            ),
            "current_python_grouped_hutch_ustat_peak_model": (
                current_hutchinson_python_peak
            ),
            "current_python_grouped_trait_peak_model": current_trait_python_peak,
            "current_python_grouped_workflow_maximum": current_python_workflow_peak,
        },
        "fit_scratch_bytes": {
            "one_normal_equation": equation_bytes,
            "retained_all_loo_equations_current_fitter": retained_loo_equations,
            "fit_result_core_without_optional_surfaces": fit_result_core,
        },
        "operation_counts": {
            "gram_probe_tiles": gram_tiles,
            "gram_source_genotype_gemms": gram_tiles * source_gemms_per_gram_tile,
            "gram_target_genotype_gemms": gram_tiles * target_gemms_per_gram_tile,
            "gram_total_genotype_gemms": gram_tiles
            * (source_gemms_per_gram_tile + target_gemms_per_gram_tile),
            "gram_action_assembly_scalar_terms_upper_bound": (
                n_reference * gram_probes * p_genetic * 2
            ),
            "gram_reduction_multiply_add_pairs": (
                n_reference * gram_probes * p_genetic**2
            ),
            "same_person_probe_tiles": same_person_tiles,
            "same_person_ideal_genotype_gemms": same_person_tiles * k_count,
            "same_person_current_python_feature_gemms": (
                same_person_tiles * k_count * q_count
            ),
            "trait_decode_passes": 1,
            "trait_decoded_blocks": trait_blocks,
            "trait_score_multi_rhs_gemms": trait_blocks,
            "trait_projected_feature_gemms": trait_blocks * q_count,
            "exact_dense_kernel_genotype_gemms": exact_kernel_gemms,
            "exact_contribution_kernel_feature_gemms": (
                exact_contribution_kernel_feature_gemms
            ),
            "approximate_loo_small_system_solves": groups + 1,
        },
        "rank_and_condition": {
            "normal_matrix_dimension": p_total,
            "symmetric_matrix_entries": p_total * (p_total + 1) // 2,
            "condition_expectation": "unknown_without_pilot_matrix",
            "more_probes_fix_structural_collinearity": False,
        },
    }
    public_request = AnnotationResourceRequest(
        n_reference=n_reference,
        n_study=n_study,
        n_variants=m_variants,
        k=k_count,
        q=q_count,
        h=residual_count,
        loo_groups=groups,
        gram_probes=gram_probes,
        same_person_probes=same_person_probes,
        probe_tile_size=probe_tile,
        memory_cap_bytes=memory_cap_bytes,
        reference_method="hutchinson",
        dtype_bytes=FLOAT64_BYTES,
    )
    public_estimate = estimate_annotation_resources(public_request)
    selected_tile = int(public_estimate.selected_probe_tile_size)
    public_gram_tiles = (
        0 if selected_tile == 0 else _ceil_div(gram_probes, selected_tile)
    )
    public_expected = {
        "p_genetic": p_genetic,
        "p_total": p_total,
        "operator_peak_bytes": _bytes(
            p_total**2
            + 3 * p_genetic**2
            + n_reference * p_genetic
            + n_reference * selected_tile * p_genetic
            + q_count * m_variants * selected_tile
            + k_count * n_reference * selected_tile
        ),
        "current_python_peak_bytes": _bytes(
            q_count * n_reference * m_variants
            + p_genetic * q_count * m_variants * max(selected_tile, 1)
            + n_reference * selected_tile * p_genetic
            + n_reference * gram_probes
            + m_variants * same_person_probes
            + groups * p_genetic**2
        ),
        "buffer_bytes.normal_matrix": _bytes(p_total**2),
        "buffer_bytes.operator_action_tile": _bytes(
            n_reference * selected_tile * p_genetic
        ),
        "buffer_bytes.operator_source_tile": _bytes(
            q_count * m_variants * selected_tile
        ),
        "buffer_bytes.operator_annotation_target_tile": _bytes(
            k_count * n_reference * selected_tile
        ),
        "buffer_bytes.same_person_persistent": _bytes(
            n_reference * p_genetic + p_genetic**2
        ),
        "storage_bytes.grouped_reference_contribution_bytes": (
            grouped_reference_contributions
        ),
        "storage_bytes.grouped_reference_total_bytes": grouped_reference_total,
        "storage_bytes.snp_reference_contribution_bytes": (snp_reference_contributions),
        "storage_bytes.snp_reference_total_bytes": snp_reference_total,
        "storage_bytes.grouped_trait_contribution_bytes": (grouped_trait_contributions),
        "storage_bytes.snp_trait_contribution_bytes": snp_trait_contributions,
        "storage_bytes.grouped_trait_total_bytes": grouped_trait_total,
        "storage_bytes.snp_trait_total_bytes": snp_trait_total,
        "operation_counts.source_genotype_products": q_count * public_gram_tiles,
        "operation_counts.annotation_target_genotype_products": (
            k_count * q_count * public_gram_tiles
        ),
        "operation_counts.trait_decode_passes": 1,
    }
    public_observed: dict[str, Any] = {
        "p_genetic": public_estimate.p_genetic,
        "p_total": public_estimate.p_total,
        "operator_peak_bytes": public_estimate.operator_peak_bytes,
        "current_python_peak_bytes": public_estimate.current_python_peak_bytes,
    }
    for namespace in ("buffer_bytes", "storage_bytes", "operation_counts"):
        values = getattr(public_estimate, namespace)
        for key in values:
            public_observed[f"{namespace}.{key}"] = values[key]
    comparisons = {
        name: {
            "expected": expected,
            "observed": public_observed.get(name),
            "exact": public_observed.get(name) == expected,
        }
        for name, expected in public_expected.items()
    }
    independent["public_resource_estimate"] = asdict(public_estimate)
    independent["public_formula_audit"] = {
        "comparison_semantics": (
            "independent integer arithmetic; complete totals include annotation "
            "mass tables; grouped object inventory separately includes int64 counts"
        ),
        "comparisons": comparisons,
        "all_exact": all(value["exact"] for value in comparisons.values()),
        "mismatches": [
            name for name, value in comparisons.items() if not value["exact"]
        ],
    }
    return independent


def main() -> None:
    os.umask(0o077)
    parser = _parser()
    args = parser.parse_args()
    args.q_values = _integer_list(parser, args.q_values, "--q-values")
    args.k_values = _integer_list(parser, args.k_values, "--k-values")
    _validate(parser, args)
    output_path = args.output_dir / OUTPUT_NAME
    if output_path.exists() and not args.overwrite:
        parser.error(
            f"output already exists; choose a fresh directory or pass --overwrite: "
            f"{output_path}"
        )

    rss_before = _rss_bytes()
    cap_bytes = int(args.memory_cap_gib * 2**30)
    cases = [
        _case(
            n_reference=args.n_reference,
            n_study=args.n_study,
            m_variants=args.m,
            q_count=q_count,
            k_count=k_count,
            groups=args.loo_groups,
            residual_count=args.residual_components,
            gram_probes=args.gram_probes,
            same_person_probes=args.same_person_probes,
            probe_tile=args.probe_tile_size,
            variant_probe_tile=args.variant_probe_tile_size,
            trait_block=args.trait_block_size,
            probe_panel_policy=args.probe_panel_policy,
            memory_cap_bytes=cap_bytes,
        )
        for k_count in args.k_values
        for q_count in args.q_values
    ]
    cap_peak_key = (
        "current_python_grouped_workflow_maximum"
        if args.cap_backend == "current_python_grouped_hutch_ustat"
        else "grouped_operator_workflow_maximum"
    )
    over_cap = [
        {
            "q": case["dimensions"]["q"],
            "k": case["dimensions"]["k"],
            "modeled_peak_bytes": case["phase_peak_bytes"][cap_peak_key],
        }
        for case in cases
        if case["phase_peak_bytes"][cap_peak_key] > cap_bytes
    ]
    rss_after = _rss_bytes()
    formula_mismatches = [
        {
            "q": case["dimensions"]["q"],
            "k": case["dimensions"]["k"],
            "fields": case["public_formula_audit"]["mismatches"],
        }
        for case in cases
        if not case["public_formula_audit"]["all_exact"]
    ]
    payload = {
        "kind": "summit.context.annotation_resource_dry_run",
        "schema_version": 1,
        "dimension_only": True,
        "large_numeric_arrays_allocated": False,
        "implementation": (
            "public estimator plus independent Python integer arithmetic; no "
            "dimension-sized arrays"
        ),
        "configuration": {
            "n_reference": args.n_reference,
            "n_study": args.n_study,
            "m_variants": args.m,
            "q_values": list(args.q_values),
            "k_values": list(args.k_values),
            "loo_groups": args.loo_groups,
            "residual_components": args.residual_components,
            "gram_probes": args.gram_probes,
            "same_person_probes": args.same_person_probes,
            "probe_tile_size": args.probe_tile_size,
            "variant_probe_tile_size": args.variant_probe_tile_size,
            "trait_block_size": args.trait_block_size,
            "probe_panel_policy": args.probe_panel_policy,
            "cap_backend": args.cap_backend,
            "hard_memory_cap_bytes": cap_bytes,
        },
        "formula_scope": {
            "included": (
                "float64 contextual moments, grouped/SNP approximate-LOO arrays, "
                "probe/action panels, current fit scratch, and dense-development "
                "lower bounds"
            ),
            "excluded": (
                "caller-owned genotype/context/fixed-effect inputs, Python object "
                "headers, BLAS-private workspaces, compression overhead, and optional "
                "context-surface grids"
            ),
            "cap_target": cap_peak_key,
            "measured_or_extrapolated": "dimension_formula_extrapolation",
        },
        "process_rss_bytes": {
            "before_calculation_high_water": rss_before,
            "after_calculation_high_water": rss_after,
            "increase_upper_bound": max(0, rss_after - rss_before),
        },
        "cases": cases,
        "hard_cap": {
            "status": "refuse_over_cap" if over_cap else "within_cap",
            "over_cap_cases": over_cap,
        },
        "public_formula_gate": {
            "status": "mismatch" if formula_mismatches else "exact",
            "mismatches": formula_mismatches,
        },
        "verdict": (
            "refuse" if over_cap else "review" if formula_mismatches else "pass"
        ),
    }
    args.output_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    args.output_dir.chmod(0o700)
    output_path.write_text(
        json.dumps(payload, sort_keys=True, indent=2) + "\n", encoding="utf-8"
    )
    output_path.chmod(0o600)
    if over_cap:
        raise SystemExit(2)
    if formula_mismatches:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
