from dataclasses import replace
from types import SimpleNamespace
import numpy as np
import pytest

from summit.context.cross_trait_gram import (exposure_factor, saved, reconstruct_ordered,
    orientation_matrix, ordered_diagonals, same_person, chromosome_gram,
    within_trait_equations)
from summit.context.spec import ContextPairIndex
from summit.ldscore.generalized_gxe_chromosome import (
    ChromosomeMoments, transferred_chromosome_equations)


@pytest.mark.parametrize('q', [1, 2, 3, 5])
def test_commuting_reconstruction_and_pair_order(q):
    rng = np.random.default_rng(610+q)
    # Independent symmetric directional moments, not generated by the inverse.
    r = rng.normal(size=(q, q, 7, 7))
    r = (r+r.swapaxes(0,1))/2
    r = (r+r.swapaxes(2,3))/2
    c = np.einsum('acjm,bdjm->abcd', r, r).reshape(q*q,q*q)
    pairs = [(p.q,p.r) for p in ContextPairIndex(q).entries]
    assert pairs[:q] == [(a,a) for a in range(q)]
    expected = np.zeros((len(pairs),len(pairs)))
    for i,(a,b_) in enumerate(pairs):
        for j,(c_,d) in enumerate(pairs):
            for a1,b1 in ({(a,b_),(b_,a)}):
                for c1,d1 in ({(c_,d),(d,c_)}):
                    expected[i,j] += c[a1*q+b1,c1*q+d1]
    np.testing.assert_allclose(saved(c,q),expected,rtol=1e-14,atol=1e-14)
    np.testing.assert_allclose(reconstruct_ordered(expected,q),c,rtol=1e-12,atol=1e-12)
    batch=np.stack([expected,3*expected])
    np.testing.assert_allclose(reconstruct_ordered(batch,q),np.stack([c,3*c]),rtol=1e-12,atol=1e-12)


def test_exposure_factor_overlap_exact_enumeration():
    rng=np.random.default_rng(21); phi=np.c_[np.ones(11),rng.normal(size=(11,2))]
    x=np.array([0,1,3,4,7,8]); y=np.array([1,2,3,6,8,10])
    expected=np.zeros((9,9))
    for i in x:
        for j in y:
            if i != j:
                v=np.outer(phi[i],phi[j]).ravel()
                expected+=np.outer(v,v)
    np.testing.assert_allclose(exposure_factor(phi,x,y),expected,atol=1e-13)
    assert expected[0,0]==len(x)*len(y)-len(np.intersect1d(x,y))
    assert exposure_factor(phi)[0,0]==110
    np.testing.assert_allclose(exposure_factor(phi,y,x).reshape(3,3,3,3).transpose(1,0,3,2).reshape(9,9),expected,atol=1e-13)
    with pytest.raises(ValueError,match='sorted'):
        exposure_factor(phi,x[::-1],y)


def test_diagonal_expansion_and_overlap():
    rng=np.random.default_rng(22); q=3; phi=np.c_[np.ones(11),rng.normal(size=(11,2))]
    pairs=ContextPairIndex(q).entries
    d=np.stack([(1 if p.q==p.r else 2)*phi[:,p.q]*phi[:,p.r] for p in pairs])
    expected=np.einsum('na,nb->abn',phi,phi).reshape(9,11)
    np.testing.assert_array_equal(ordered_diagonals(d,q),expected)
    x=np.arange(8);y=np.arange(3,11)
    np.testing.assert_allclose(same_person(d,x,y,q=q),expected[:,3:8]@expected[:,3:8].T)
    np.testing.assert_array_equal(same_person(d,np.arange(3),np.arange(4,8),q=q),np.zeros((9,9)))


def test_factorized_assembly_and_block_mass_restoration():
    rng=np.random.default_rng(43);n=19;q=3;p=6;k=2
    phi=np.c_[np.ones(n),rng.normal(size=(n,2))]
    pairs=ContextPairIndex(q).entries
    d=np.vstack([np.stack([(1 if t.q==t.r else 2)*phi[:,t.q]*phi[:,t.r] for t in pairs])*s for s in (.3,.7)])
    masses=np.array([[2.,1.],[3.,4.],[5.,5.]])
    total=masses.sum(0)
    dr=d@d.T
    ell=np.array([[.01,.002],[.002,.008]])
    fr=saved(exposure_factor(phi),q)
    t=np.zeros((3,k*p,k*p))
    fractions=masses/total
    for b in range(3):
        for a in range(k):
            for c in range(k):
                ix=np.s_[a*p:(a+1)*p,c*p:(c+1)*p]
                t[b][ix]=fractions[b,a]*(dr[ix]+ell[a,c]*fr)
    inverse=np.repeat(total,p)
    ref=SimpleNamespace(n_samples=n,num_basis=q,annotation_names=('a','b'),
        block_directed=t*inverse[None,:,None]*inverse[None,None,:]/(n-3)**2,
        residual_rank=n-3,block_masses=masses)
    x=np.arange(14);y=np.arange(5,n)
    got=chromosome_gram(ref,d,phi,x,y,global_masses=total)
    expected=np.kron(ell,exposure_factor(phi,x,y))+same_person(d,x,y,q=q)
    np.testing.assert_allclose(got.matrix,expected,atol=1e-12,rtol=1e-12)
    assert got.diagnostics['factorization_residual'].max()<1e-14
    plus=chromosome_gram(ref,d,phi,x,y,global_masses=total,mode='factorized_plus_residual')
    np.testing.assert_allclose(plus.matrix,expected,atol=1e-12,rtol=1e-12)
    with pytest.raises(ValueError,match='requires'):
        chromosome_gram(ref,d,phi,x,y,global_masses=total,mode='legacy_transport_exact')


def test_legacy_within_trait_is_bit_exact_full_and_deleted():
    rng=np.random.default_rng(91);q=2;p=3;n=91;ns=73
    ref=[];study=[]
    for ch in (1,2):
        directed=rng.normal(size=(2,p,p));directed=np.einsum('bij,bkj->bik',directed,directed)
        c=ChromosomeMoments(str(ch),'master',('all',),('trait',),q,n,n-2,
            np.array([2*ch-2,2*ch-1]),np.array([[9.],[11.]]),directed,
            rng.normal(size=(2,p,1)),rng.normal(size=(2,p,2)))
        ref.append(c);study.append(replace(c,cohort_identity='study',n_samples=ns,residual_rank=ns-2,
            block_genetic_rhs=c.block_genetic_rhs*.8,block_genetic_residual=c.block_genetic_residual*.8))
    options=dict(reference_residual_gram=np.diag([n-2.,float(n)]),
        reference_residual_traces=np.array([n-2.,0.]),reference_same_person=np.eye(p),
        residual_gram=np.diag([ns-2.,float(ns)]),residual_rhs=np.ones((2,1)),
        residual_traces=np.array([ns-2.,0.]),residual_names=('one','context'))
    for deleted in ((),(1,),(0,3)):
        expected=transferred_chromosome_equations(ref,study,deleted_blocks=deleted,**options)
        got=within_trait_equations(ref,study,reference_diagonals=None,phi=None,rows=None,
            mode='legacy_transport',same_person_mode='scaled',deleted_blocks=deleted,deletion_method='legacy',**options)
        for name in ('matrix','rhs','reference_genetic_gram','transferred_genetic_gram'):
            np.testing.assert_array_equal(getattr(got,name),getattr(expected,name))
